media:
  input: src/assets
  output: ../../assets

content:
  - name: posts
    label: Posts
    type: collection
    path: src/content/blog
    filename: "{primary}.md"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Short description
        type: text
        required: true
      - name: pubDate
        label: Publish date
        type: date
        required: true
      - name: body
        label: Content
        type: rich-text